version: "3.9"  # optional since v1.27.0

services:
  app:
    build:
      context: ./django/
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/static
    env_file:
      - ./.env/dev.env

  # app2:
  #   build:
  #     context: ./django2/
  #   volumes:
  #     - ./django2/:/usr/src/app/
  #     - static_files:/usr/src/app/static
  #   env_file:
  #     - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/static
      - ./nginx/html/:/home/html/
      - ./nginx/secure/:/home/secure/
      - ./nginx/.htpasswd:/etc/pwd/.htpasswd

  dns:
    build:
      context: ./dns
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

volumes:
  static_files: